SELECT
    f.PRODUCT_ID,
    f.PRODUCT_NAME,
    SUM(f.PRICE * o.AMOUNT) TOTAL_SALES
FROM
    FOOD_PRODUCT f
    JOIN FOOD_ORDER o ON f.PRODUCT_ID = o.PRODUCT_ID
WHERE
    o.PRODUCE_DATE LIKE '2022-05%'
GROUP BY
    PRODUCT_ID,
    PRODUCT_NAME
ORDER BY
    TOTAL_SALES DESC,
    PRODUCT_ID;